import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./_components/NavigationBar";
import CallToAction from "./_components/CallToAction";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "msmith.codes",
    description: "Generated by create next app",
};

interface RootLayoutProps
{
    children : React.ReactNode;
}

export default function RootLayout(props : RootLayoutProps) 
{
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <NavigationBar />
                {props.children}
                <CallToAction />
            </body>
        </html>
  );
}
